# Generated by Django 5.0.2 on 2024-06-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('date', models.DateField(null=True)),
                ('user_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'TasksTable',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('imageType', models.IntegerField()),
                ('state', models.IntegerField(blank=True, null=True)),
                ('table_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.taskstable')),
            ],
            options={
                'db_table': 'Tasks',
                'ordering': ['id'],
            },
        ),
    ]
