# Generated by Django 5.0.2 on 2024-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstable',
            name='shared_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
