# Generated by Django 5.0.2 on 2024-08-01 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstable',
            name='share_with',
        ),
        migrations.AddField(
            model_name='taskstable',
            name='table_color',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='taskstable',
            name='table_image',
            field=models.FileField(default='', upload_to='tasks'),
        ),
        migrations.CreateModel(
            name='Tables_And_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_by', models.CharField(default='', max_length=50)),
                ('share_with', models.EmailField(default='', max_length=50)),
                ('table_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.taskstable')),
                ('user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Tables_and_Users',
                'ordering': ['id'],
            },
        ),
    ]
