# Generated by Django 5.0.2 on 2024-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_taskstable_share_with_taskstable_table_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables_and_users',
            name='table_image',
            field=models.FileField(default='', upload_to='tasks'),
        ),
    ]
