# Generated by Django 5.0.2 on 2024-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_tables_and_users_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables_and_users',
            name='table_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='tasksU'),
        ),
    ]
