# Generated by Django 5.0.2 on 2024-08-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_tables_and_users_table_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables_and_users',
            name='table_color',
            field=models.CharField(default='', max_length=8),
        ),
    ]
