# Generated by Django 5.0.2 on 2025-11-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_tables_and_users_table_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables_and_users',
            name='table_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='tasks'),
        ),
    ]
