# Generated by Django 5.0.2 on 2025-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_tables_and_users_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstable',
            name='table_image',
            field=models.FileField(blank=True, null=True, upload_to='tasks'),
        ),
    ]
