import { Inter } from "next/font/google";
import Navbar from "./NavBar/navbar";
import "./globals.css";
import { UserContextProvider } from "./context/userContext";
import { TasksContextProvider } from "./context/tasksContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="h-screen bg-white">
        <TasksContextProvider>
          <UserContextProvider>
            <Navbar/>
            {children}
          </UserContextProvider>
        </TasksContextProvider>
      </body>
    </html>
  );
}
