version: 'latest'
services:
     web:
       build:
          context: .
          dockerfile: ./Dockerfile
       #command: npm run dev
       ports:
         - "3000:3000"
       volumes:
          - ./var/_data:/front_volume
       networks:
         - tasks_nw
networks:
  tasks_nw:
      driver: bridge
volumes:
  tasks_front_volume:
     external: true


